-- Insert room test data
INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOMNUMBER, SEATS) VALUES (TRUE, 'A', '001', 45);
INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOMNUMBER, SEATS) VALUES (TRUE, 'A', '002', 40);
INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOMNUMBER, SEATS) VALUES (FALSE, 'A', '004', 40);
